### ISSUE TITLE
how can I make array as function argument in c++?

### ISSUE THREAD

**Issue by ArtashesSoghomonian** [MrMimic/data-scientist-roadmap#12]
When I want to put in x function argument a created array it doesn't give me an error, but when I am putting not created array it gives me an error. Here is code
```
```
#include <iostream>
#include <conio.h>
using namespace std;

void x(int arr[]){
    cout << arr[0];
}

int main(){
    x({1,2,3,4,5});
    getch();
    return 0;
}

```
```

**Comment by MrMimic** [comment]
I don't even understand what this question is about or why it has been posted here.
