### ISSUE TITLE
What's the license of this repository? There's no LICENSE.txt file.

### ISSUE THREAD

**Issue by cleuton** [MrMimic/data-scientist-roadmap#3]
Hi, I want to collaborate with this repository, and I want to use some of its resources too. But there is no LICENSE.txt file, so, I don't know how will my contributions be used. 

For example, that excellent Map in the README. I know it was created by Swami Chandrasekaran, but there is no information about licenses. Can I use that picture? 

I suggest you to deal with all contributors and choose a license for the whole repository contents, such as Creative Commons or Apache.

**Comment by MrMimic** [comment]
Hi.
I'm going to push a LICENCE.txt right now.
I saw many people using this map, especially on LinkedIn. I emailed M. Chandrasekaran to get some informations about, but he didn't answer ftm.
